### ISSUE TITLE
Python 3.9 required?

### ISSUE THREAD

**Issue by jd-foster** [captn3m0/pystitcher#17]
Thanks for the great code, it worked well for me putting books back together from chapters in Elsevier.
The only issue I had was that it required using Python 3.9 at a minimum.
I initially had an error under Python 3.7, complaining about line 56 of `skeleton.py` with reference to `argparse.BooleanOptionalAction` ; I lost the actual error message e.g see [here](https://bugs.python.org/issue42194) for related.

**Comment by captn3m0** [comment]
Thanks for the report.

**Comment by captn3m0** [comment]
Thanks for tracking it down, was much easier to fix :)

Pushed a new release to PyPI (v1.0.3) with the fix (and a few more pending changes).

Changelog: https://github.com/captn3m0/pystitcher/releases/tag/v1.0.3
